language: python
cache: pip

addons:
  apt:
    packages:
      - swig

matrix:
  include:
    - python: 3.6
      env: TOXENV=py35-flask1.0
    - python: 3.6
      env: TOXENV=flake8,isort

install:
    - pip install tox

script: tox

deploy:
  provider: pypi
  user: tim_heap
  password: $PYPI_PASSWORD
  on:
    python: 3.6
    condition: $( ./setup.py --version ) == $TRAVIS_TAG
    branch: master
    tags: true

# vim: sw=2 expandtab
