language: python
cache: pip

addons:
  apt:
    packages:
      - swig

matrix:
  include:
    - python: 3.6
      env: TOXENV=py35-flask1.0
    - python: 3.6
      env: TOXENV=flake8,isort

install:
    - pip install tox

script: tox

# vim: sw=2 expandtab
